package com.example.tgbot.telegram.panels;

public enum PanelType {
    MAIN_MENU,
    GENERATE_IMAGE,
    GENERATE_MUSIC,
    GENERATE_VIDEO,
    GET_GIFT,
    KLING_SETUP,
    KLING_DURATION_SELECTION,
    KLING_FORMAT_SELECTION,
    KLING_AFTER_PROMPT,
    MAIN_FILE_READY,
    NANO_BANANA_PRE_PROMPT,
    SORA_2_FORMAT_SELECTION,
    SORA_2_AFTER_PROMPT,
    NANO_BANANA_SETUP,
    PAID_PACKAGE_SETUP,
    RECHARGE_BALANCE,
    SIMPLE_MESSAGE,
    SORA_2_SETUP,
    SUNO_SETUP,
    SUNO_AFTER_GENRE_SELECTION,
    SUNO_AFTER_PROMPT
}
