package com.example.tgbot.telegram.panels;

public enum PanelType {
    MAIN_MENU,
    NANO_BANANA_FORMAT_SELECTION,
    GENERATE_MUSIC,
    GENERATE_VIDEO,
    GET_GIFT,
    KLING_SETUP,
    KLING_DURATION_SELECTION,
    KLING_FORMAT_SELECTION,
    KLING_AFTER_PROMPT,
    MAIN_FILE_READY,
    SORA_2_FORMAT_SELECTION,
    SORA_2_AFTER_PROMPT,
    NANO_BANANA_SETUP,
    AFTER_PAID_PACKAGE_SELECTED,
    RECHARGE_BALANCE,
    SIMPLE_MESSAGE,
    SORA_2_SETUP,
    SUNO_SETUP,
    SUNO_AFTER_PROMPT,
    SUNO_GENRE_SELECTION
}
